name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [10, 12, 14]
        name: Node ${{ matrix.node }}
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./build/lcov.info
                  parallel: true
    coverage:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true
